[build]
  command = """
    git clone https://github.com/flutter/flutter.git;
    export PATH="$PATH:`pwd`/flutter/bin";
    flutter precache;
    flutter pub get;
    flutter build web;
    cd netlify/functions && npm install
  """
  publish = "build/web"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
